### ISSUE TITLE
请问作者大大可以支持国服嘛

### ISSUE THREAD

**Issue by Baozi0312** [akira0245/EasyZoom#4]
看到只支持API8，就想请问一下有可能出一个国服支持的版本嘛 QvQ 可以突破物体限制的功能不卡视角太好用了

**Comment by akira0245** [comment]
[latest.zip](https://github.com/akira0245/EasyZoom/files/10577905/latest.zip)
这个是api7的 国服应该可以用

**Comment by Baozi0312** [comment]
谢谢大大！！可以用！
